version: 2

# Build documentation in the docs/ directory with Phinx
sphinx:
  configuration: docs/conf.py
  
# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  
python:
  version: 3.8
