language: python
python:
  - "3.8" 
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pylint
script:
#  - python3 -m unittest -v
  - coverage run -m unittest discover
  - pylint source/*
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd docs; sphinx-apidoc --ext-autodoc -o . ../source/; sphinx-build -a . ./_build/
  - cd _static; pyreverse ../../source/calculator -a1 -s1 -o png

